ame: Deploy Frontend and Backend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: frontend
        run: npm install
      - name: Build
        working-directory: frontend
        run: npm run build
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ secrets.GCP_PROJECT_ID }}

  build-and-deploy-backend:
    runs-on: ubuntu-latest
    needs: build-and-deploy-frontend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Build & push container
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/women-safety-backend:latest backend
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy women-safety-backend --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/women-safety-backend:latest --region us-central1 --platform managed --allow-unauthenticated
