name: Deploy Static Site to Firebase Hosting (Service Account)

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
   
      - name: Checkout repository
        uses: actions/checkout@v4

    
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v13.25.0
        with:
          args: deploy --only hosting --project women-safest-route
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
